// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcyCoIpe19Mzk5_CM4W3b_yrkHIovWmc',
    appId: '1:266337699849:web:af3b4589d5b082cae450d8',
    messagingSenderId: '266337699849',
    projectId: 'messageapp-64f7d',
    authDomain: 'messageapp-64f7d.firebaseapp.com',
    storageBucket: 'messageapp-64f7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHNntRrCAxMB63izz7JkvMlZLdNGCUrM',
    appId: '1:266337699849:android:bf8c1a14af97a60ce450d8',
    messagingSenderId: '266337699849',
    projectId: 'messageapp-64f7d',
    storageBucket: 'messageapp-64f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCicMvOrDNnNL35fGnLdhMfD0lAe095amI',
    appId: '1:266337699849:ios:e73864111a372ac0e450d8',
    messagingSenderId: '266337699849',
    projectId: 'messageapp-64f7d',
    storageBucket: 'messageapp-64f7d.appspot.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCicMvOrDNnNL35fGnLdhMfD0lAe095amI',
    appId: '1:266337699849:ios:e73864111a372ac0e450d8',
    messagingSenderId: '266337699849',
    projectId: 'messageapp-64f7d',
    storageBucket: 'messageapp-64f7d.appspot.com',
    iosBundleId: 'com.example.messageapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcyCoIpe19Mzk5_CM4W3b_yrkHIovWmc',
    appId: '1:266337699849:web:26648b2480e6204be450d8',
    messagingSenderId: '266337699849',
    projectId: 'messageapp-64f7d',
    authDomain: 'messageapp-64f7d.firebaseapp.com',
    storageBucket: 'messageapp-64f7d.appspot.com',
  );
}
